### ISSUE TITLE
Question: Additional Guidance on Using Sphere

### ISSUE THREAD

**Issue by stevemarin** [tianluyuan/sphere#2]
Hi!  I stumbled upon this package, and it looks great.  For my application, I have spatial ellipses (lat/long, major/minor axes, orientation) on the globe representing locations of some entities.  I want to map these ellipses to distributions on a sphere so I can sample from them.  I'm struggling to understand how to map the parameters I have to one of the constructors you provide.  Are you aware of any references that may help?  I've tried Googling to no avail!  Either way, thank you so much for this package!

**Comment by tianluyuan** [comment]
The orientation mapping should be straightforward, but it's trickier to map the major/minor axes. If the major/minor axes are angular distances from the center and the ellipse represents the 39.3% level contour around the highest probability density region, you can to good approximation map major/minor axes `(a,b)` to the Kent distribution as `kappa = (a**2 + b**2)/(2 * a**2 *b**2)` and `beta = (a**2 - b**2)/(4 * a**2 *b**2)` such that `pdf = fb8(np.pi/2-lat, long, orientation, kappa, beta)`. This approximation holds for small values of `a` as shown below, and is a consequence of the Kent distribution reducing to a ~2D gaussian for large values of `kappa`. You can find more details in Kent ([1982](https://doi.org/10.1111/j.2517-6161.1982.tb01189.x)). If your ellipses correspond to some other percentile level contour you can assume a 2D gaussian to scale the major/minor axes accordingly.

However, as the ellipse grows larger the approximation breaks down and you may need to solve for `kappa` and `beta` numerically.

```
import numpy as np
import warnings
import sphere.distribution as sd
import logging
logging.getLogger().setLevel(logging.ERROR)

majors = np.radians([5, 10, 20])
minors = np.radians([1, 3])
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for a in majors:
        for b in minors:
            if b > a:
                continue
            kappa = (a**2 + b**2)/(2 * a**2 *b**2)
            beta = (a**2 - b**2)/(4 * a**2 *b**2)

            pdf = sd.fb8(np.pi/2,0,0, kappa, beta)
            thetas, phis = pdf.contour(39.3)
            print(f'Ellipse (major, minor) = ({np.degrees(a):.2f}, {np.degrees(b):.2f})')
            print(f'Kent 39% (major, minor) = ({max(np.degrees(thetas-np.pi/2)):.2f}, {max(np.degrees(phis)):.2f})')
```

output
```
Ellipse (major, minor) = (5.00, 1.00)
Kent 39% (major, minor) = (4.86, 0.98)
Ellipse (major, minor) = (5.00, 3.00)
Kent 39% (major, minor) = (5.00, 3.01)
Ellipse (major, minor) = (10.00, 1.00)
Kent 39% (major, minor) = (8.20, 0.92)
Ellipse (major, minor) = (10.00, 3.00)
Kent 39% (major, minor) = (9.54, 2.91)
Ellipse (major, minor) = (20.00, 1.00)
Kent 39% (major, minor) = (10.34, 0.84)
Ellipse (major, minor) = (20.00, 3.00)
Kent 39% (major, minor) = (15.29, 2.69)
```
