### ISSUE TITLE
Possibility to pass numpy random generator as argument in rvs

### ISSUE THREAD

**Issue by MehdiN** [tianluyuan/sphere#3]
Hello! I am using your package to sample quaternions in non isotropic distributions, in particular Kent distribution.

I would like to suggest a small addition to make sampling from seeded generators easier by changing the class method `rvs(self, n_samples=None)` to `rvs(self, n_samples=None,random_gen=None)` by adding the possibility to pass a Numpy generator as argument like the model of the [rvs_continuous class](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html#scipy.stats.rv_continuous) of scipy.stats.

For instance, if using `scipy.stats`:
```python
    def _rvs_helper(self,random_gen=None):
        num_samples = 10000
        xs = gauss(0, 1).rvs((num_samples, 3),random_state=random_gen)
        xs = np.divide(xs, np.reshape(norm(xs, 1), (num_samples, 1)))
        lpvalues = self.log_pdf(xs, normalize=False)
        lfmax = self.log_pdf_max(normalize=False)
        shifted = lpvalues - lfmax
        return xs[uniform(0, 1).rvs(num_samples,random_state=random_gen) < np.exp(shifted)]
``` 

Where `random_state` is eitheir a `None`, `int` or  [numpy.random.generator ](https://numpy.org/devdocs/reference/random/generator.html#numpy.random.Generator).

another possibility if using `numpy.random`

```python
from numpy.random import default_gen

# [...]

    def _rvs_helper(self,random_gen=None):
        num_samples = 10000
        if random_gen is None:
            random_gen = default_gen()
        xs = random_gen.normal(0, 1,(num_samples,3))
        xs = np.divide(xs, np.reshape(norm(xs, 1), (num_samples, 1)))
        lpvalues = self.log_pdf(xs, normalize=False)
        lfmax = self.log_pdf_max(normalize=False)
        shifted = lpvalues - lfmax
        return xs[random_gen.uniform(0, 1, num_samples) < np.exp(shift)] 
```

Thank you for your package !

**Comment by tianluyuan** [comment]
Thanks for the suggestion, that's a good idea! Would you like to submit a PR for it? Probably the first approach would be my preference, unless there's a reason for the latter.

The sampling part is one area that could be improved. It's not the most efficient and probably there are more efficient sampling algorithms that one could try.

**Comment by tianluyuan** [comment]
It turned out to be a bit more complicated than I originally thought due to the caching, so I just implemented some changes that preserve that, and allows you to pass a seed via `obj.rvs(n_samples, seed)`, where seed can be anything accepted by `np.random.default_rng`. A new version should be up on pypi as well.
